DROP SCHEMA IF EXISTS RUGBY;

CREATE SCHEMA RUGBY;
USE RUGBY;

CREATE TABLE IF NOT EXISTS Clubs
(
ClubID INT auto_increment PRIMARY KEY NOT NULL,
ClubName VARCHAR(100) NOT NULL,
HomeGround VARCHAR(100) NOT NULL,
ClubAddress VARCHAR(255),
ContactPhone VARCHAR(10),
Email VARCHAR(320)
);

CREATE TABLE IF NOT EXISTS Grades
(
GradeID INT auto_increment PRIMARY KEY NOT NULL,
GradeName VARCHAR(50),
GradeMinimumAge INT NOT NULL,
GradeMaximumAge INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Teams
(
TeamID INT auto_increment PRIMARY KEY NOT NULL,
ClubID INT NOT NULL,
TeamName VARCHAR(80) NOT NULL,
TeamGrade INT,
FOREIGN KEY (TeamGrade) REFERENCES Grades(GradeID)
ON UPDATE CASCADE
ON DELETE CASCADE,
FOREIGN KEY(ClubID) REFERENCES Clubs(ClubID)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Members
(
MemberID INT auto_increment PRIMARY KEY NOT NULL,
ClubID INT NOT NULL,
TeamID INT,
MemberFirstName VARCHAR(50) NOT NULL,
MemberLastName VARCHAR(50) NOT NULL,
Address1 VARCHAR(50),
Address2 VARCHAR(50),
City VARCHAR(30) NOT NULL,
Email VARCHAR(320) NOT NULL,
Phone VARCHAR(10),
Birthdate DATE NOT NULL,
MembershipStatus BOOL NOT NULL,
AdminAccess BOOL NOT NULL,
FOREIGN KEY (ClubID) REFERENCES Clubs(ClubID)
ON UPDATE CASCADE
ON DELETE CASCADE,
FOREIGN KEY(TeamID) REFERENCES Teams(TeamID)
ON UPDATE CASCADE
ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS Fixtures
(
FixtureID INT auto_increment PRIMARY KEY NOT NULL,
FixtureDate DATETIME NOT NULL,
HomeTeam INT NOT NULL,
AwayTeam INT NOT NULL,
HomeScore INT,
AwayScore INT,
FOREIGN KEY(HomeTeam) REFERENCES Teams(TeamID)
ON UPDATE CASCADE
ON DELETE CASCADE,
FOREIGN KEY(AwayTeam) REFERENCES Teams(TeamID)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ClubNews 
(
NewsID INT auto_increment PRIMARY KEY NOT NULL,
ClubID INT NOT NULL,
NewsHeader VARCHAR(100),
NewsByline VARCHAR(50),
NewsDate DATE,
News TEXT,
FOREIGN KEY(ClubID) REFERENCES Clubs(ClubID)
ON UPDATE CASCADE
ON DELETE CASCADE
);


